version: "2"

services: 

    azureite:
        image: mcr.microsoft.com/azure-storage/azurite
        restart: always
        ports:
        - "10001:10001"
        - "10000:10000"
        - "10002:10002"
        links: 
            - sql-server-db

    azure_function:
        build:
            context: .
            dockerfile: Dockerfile
        image: functions:1.0
        ports:
            - '8080:80'
        links: 
            - azureite
        restart: always
    

    sql-server-db:
        container_name: sql-server-db
        image: microsoft/mssql-server-linux:2017-latest
        restart: always
        ports:
            - "1433:1433"
            - "1434:1434"
        environment: 
            ACCEPT_EULA: "yes"
            MSSQL_SA_Password: "!passw0rd1985"
       
